[variables]
NODE_VERSION = "20.11.1"
HOSTNAME = "0.0.0.0"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20"]

[start]
cmd = "sh -c \"node .next/standalone/server.js & node scripts/local-cron.js & wait\""
